### ISSUE TITLE
An promising work

### ISSUE THREAD

**Issue by wangjiawen2013** [Chemios/chemios#5]
Dear,
Now I am trying to control my NE1000 pump and find chemios occasionally. I believe it's a promising framework. My major is Biomechanics and need to control many equipments in my lab. I will read chemios' documents in detail and contribute to this project. Of course, it's most likely that I need your help later!

**Comment by marcosfelt** [comment]
Hi,
Thanks so much! Right now , I am not actively working on it, but I'm hoping to make progress next year.
